"""
日系企業の判定リスト。

各要素は (グループ名, 業種, 社名の正規表現)。LCAの EMPLOYER_NAME を大文字にして先頭一致などで判定する。
上から順に判定し、最初に一致したグループに割り当てる(例:豊田通商は「トヨタ」より先に書いてあるので商社として数える)。
社名に日本の親会社名が含まれない買収先(GlobalLogic、Indeed、7-Eleven など)は個別に追加している。
漏れや誤判定を見つけたら、このファイルを直してスクリプトを再実行してください。
"""
import re
JP=[
# 金融
('野村','金融',r'^(NOMURA (HOLDING|SECURITIES|GLOBAL|AMERICA|CORPORATE|CAPITAL|ASSET)|INSTINET)'),
('みずほ','金融',r'^(MIZUHO (AMERICAS|SECURITIES|BANK|CAPITAL|MARKETS)|GREENHILL)'),
('三菱UFJ','金融',r'^(MUFG|MITSUBISHI UFJ)'),
('三井住友(SMBC)','金融',r'^(SUMITOMO MITSUI (BANKING|TRUST|FINANCE)|SMBC)'),
('大和証券','金融',r'^(DAIWA (CAPITAL|CORPORATE|SECURITIES|ASSET)|SAGENT ADVISORS|SIGNAL HILL CAPITAL)'),
('オリックス','金融',r'^ORIX'),
('SBI','金融',r'^SBI (HOLDINGS|SECURITIES|US)'),
# 保険
('東京海上','保険',r'^(TOKIO MARINE|PHILADELPHIA (INDEMNITY|INSURANCE|CONSOLIDATED)|DELPHI FINANCIAL|RELIANCE STANDARD|SAFETY NATIONAL CASUALTY|HCC (SERVICE|INSURANCE|SPECIALTY))'),
('SOMPO','保険',r'(SOMPO|^ENDURANCE SERVICES)'),
('MS&AD(三井住友海上等)','保険',r'^(MITSUI SUMITOMO|MS&AD|AIOI NISSAY)'),
('第一生命(Protective)','保険',r'^(PROTECTIVE LIFE|DAI-?ICHI LIFE)'),
('日本生命','保険',r'^(NIPPON LIFE|RESOLUTION LIFE)'),
('住友生命(Symetra)','保険',r'^SYMETRA'),
('明治安田(StanCorp)','保険',r'^(STANCORP|STANDARD INSURANCE CO)'),
# IT・通信
('日立(GlobalLogic含む)','IT・電機',r'^(HITACHI|GLOBALLOGIC)'),
('NTT(NTTデータ等)','IT・電機',r'^NTT\b'),
('富士通','IT・電機',r'^FUJITSU'),
('NEC','IT・電機',r'^NEC (CORPORATION|LABORATORIES|AMERICA|NETWORKS|DISPLAY)'),
('野村総合研究所(NRI)','IT・電機',r'^(NOMURA RESEARCH|NRI |CORE BTS)'),
('ソニー','IT・電機',r'^SONY'),
('パナソニック','IT・電機',r'^PANASONIC'),
('東芝','IT・電機',r'^TOSHIBA'),
('三菱電機','IT・電機',r'^MITSUBISHI ELECTRIC'),
('キヤノン','IT・電機',r'^CANON (USA|U\.S\.A|MEDICAL|SOLUTIONS|INFORMATION|VIRGINIA|NANOTECH|BUSINESS|FINANCIAL|HEALTHCARE)'),
('富士フイルム','IT・電機',r'^FUJIFILM'),
('リコー','IT・電機',r'^RICOH'),
('京セラ','IT・電機',r'^(KYOCERA|AVX)'),
('セイコーエプソン','IT・電機',r'^EPSON'),
('コニカミノルタ','IT・電機',r'^KONICA MINOLTA'),
('オリンパス','IT・電機',r'^OLYMPUS (CORPORATION|SURGICAL|SCIENTIFIC|AMERICA)'),
('ニコン','IT・電機',r'^NIKON'),
('楽天','IT・電機',r'^RAKUTEN'),
('リクルート(Indeed等)','IT・電機',r'^(INDEED,? INC|GLASSDOOR)'),
('ソフトバンク','IT・電機',r'^(SOFTBANK|SB ENERGY)'),
('任天堂','IT・電機',r'^NINTENDO'),
('ゲーム(スクエニ・バンナム・セガ等)','IT・電機',r'^(SQUARE ENIX|BANDAI NAMCO|SEGA OF AMERICA|CAPCOM|KONAMI|SEGA )'),
# 半導体・電子部品・機械
('東京エレクトロン','半導体・部品・機械',r'^TOKYO ELECTRON'),
('ルネサス','半導体・部品・機械',r'^RENESAS'),
('村田製作所','半導体・部品・機械',r'^MURATA'),
('TDK','半導体・部品・機械',r'^TDK'),
('キオクシア','半導体・部品・機械',r'^KIOXIA'),
('アドバンテスト','半導体・部品・機械',r'^ADVANTEST'),
('キーエンス','半導体・部品・機械',r'^KEYENCE'),
('ディスコ・SCREEN等','半導体・部品・機械',r'^(DISCO HI-TEC|SCREEN SPE|SCREEN HOLDINGS|LASERTEC|ULVAC)'),
('ローム','半導体・部品・機械',r'^ROHM SEMICONDUCTOR'),
('ニデック','半導体・部品・機械',r'^NIDEC'),
('オムロン','半導体・部品・機械',r'^OMRON'),
('ファナック','半導体・部品・機械',r'^FANUC'),
('安川電機','半導体・部品・機械',r'^YASKAWA'),
('SMC','半導体・部品・機械',r'^SMC CORPORATION OF AMERICA'),
('小松製作所','半導体・部品・機械',r'^KOMATSU'),
('クボタ','半導体・部品・機械',r'^KUBOTA'),
('ダイキン','半導体・部品・機械',r'^(DAIKIN|GOODMAN MANUFACTURING)'),
('三菱重工','半導体・部品・機械',r'^MITSUBISHI (HEAVY|POWER)'),
('住友電工','半導体・部品・機械',r'^SUMITOMO ELECTRIC'),
('横河電機','半導体・部品・機械',r'^YOKOGAWA'),
('HOYA','半導体・部品・機械',r'^HOYA (SURGICAL|OPTICAL|CORPORATION|VISION)'),
('信越化学(Shintech等)','素材・化学',r'^(SHIN-?ETSU|SHINTECH)'),
('三菱ケミカル','素材・化学',r'^MITSUBISHI CHEMICAL'),
('旭化成','素材・化学',r'^ASAHI KASEI'),
('東レ','素材・化学',r'^TORAY'),
('日本製鉄(USスチール含む)','素材・化学',r'^(NIPPON STEEL|UNITED STATES STEEL|US STEEL|U S STEEL)'),
('ブリヂストン','素材・化学',r'^(BRIDGESTONE|FIRESTONE)'),
# 自動車
('豊田通商','商社',r'^TOYOTA TSUSHO'),
('トヨタ','自動車',r'^(TOYOTA|WOVEN BY TOYOTA|DENSO|AISIN|TOYODA GOSEI|JTEKT)'),
('ホンダ','自動車',r'^(HONDA|AMERICAN HONDA)'),
('日産','自動車',r'^NISSAN'),
('SUBARU','自動車',r'^SUBARU'),
('マツダ','自動車',r'^MAZDA'),
('三菱自動車','自動車',r'^MITSUBISHI MOTORS'),
('ヤマハ','自動車',r'^YAMAHA'),
('スズキ','自動車',r'^SUZUKI MOTOR'),
('川崎重工','自動車',r'^KAWASAKI (MOTORS|HEAVY|RAIL)'),
# 商社
('三菱商事','商社',r'^(MITSUBISHI CORPORATION|MITSUBISHI INTERNATIONAL)'),
('三井物産','商社',r'^MITSUI & CO'),
('伊藤忠','商社',r'^ITOCHU'),
('住友商事','商社',r'^SUMITOMO CORPORATION'),
('丸紅','商社',r'^MARUBENI'),
('双日','商社',r'^SOJITZ'),
# 製薬・医療
('武田薬品','製薬・医療',r'^(TAKEDA|MILLENNIUM PHARMA)'),
('アステラス','製薬・医療',r'^ASTELLAS'),
('第一三共','製薬・医療',r'^DAIICHI SANKYO'),
('エーザイ','製薬・医療',r'^EISAI'),
('大塚','製薬・医療',r'^OTSUKA'),
('塩野義','製薬・医療',r'^SHIONOGI'),
('協和キリン','製薬・医療',r'^KYOWA KIRIN'),
('住友ファーマ','製薬・医療',r'^SUMITOMO PHARMA'),
('テルモ','製薬・医療',r'^TERUMO'),
('シスメックス','製薬・医療',r'^SYSMEX'),
('中外製薬','製薬・医療',r'^CHUGAI'),
# 消費財・小売・サービス
('セブン&アイ(7-Eleven)','消費財・小売・サービス',r'^7-ELEVEN'),
('ファーストリテイリング','消費財・小売・サービス',r'^(UNIQLO|FAST RETAILING)'),
('資生堂','消費財・小売・サービス',r'^SHISEIDO'),
('花王','消費財・小売・サービス',r'^KAO (USA|CORPORATION|SPECIALTIES)'),
('サントリー','消費財・小売・サービス',r'^(SUNTORY|BEAM SUNTORY)'),
('キリン','消費財・小売・サービス',r'^KIRIN'),
('味の素','消費財・小売・サービス',r'^AJINOMOTO'),
('電通','消費財・小売・サービス',r'^(DENTSU|MERKLE,? INC|MERKLE SOFTWARE|CARAT USA)'),
('博報堂','消費財・小売・サービス',r'^HAKUHODO'),
('アシックス','消費財・小売・サービス',r'^ASICS (DIGITAL|AMERICA|NORTH)'),
('ヤクルト・キッコーマン・日清等','消費財・小売・サービス',r'^(YAKULT|KIKKOMAN|NISSIN FOODS)'),
('建設(鹿島・大林・清水等)','消費財・小売・サービス',r'^(KAJIMA|OBAYASHI|SHIMIZU NORTH|TAISEI|WEBCOR)'),
]
